/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#f5c518',
        'on-primary': '#1a1a1a',
        'primary-soft': '#fde68a',
        'primary-deep': '#d4a000',
        lemon: '#f5c518',
        'lemon-soft': '#fde68a',
        'lemon-deep': '#d4a000',
        ink: '#0f172a',
        'ink-soft': '#334155',
        'ink-muted': '#4b5563',
        'dark-ink': '#f8fafc',
        'dark-ink-soft': '#cbd5e1',
        'dark-bg': '#0f172a',
        'dark-bg-2': '#1e293b',
        'dark-bg-3': '#334155',
        'dark-border': '#334155',
        surface: '#ffffff',
        'on-surface': '#0f172a',
        'surface-container': '#f8fafc',
        'surface-container-low': '#f1f5f9',
        'surface-container-high': '#e2e8f0',
        'on-surface-variant': '#64748b',
        cream: '#fffef9',
        'cream-elev': '#ffffff',
        'cream-veil': '#f8f6f0',
        'cream-deep': '#fdfbf7',
        border: '#e2dfd6',
        'border-soft': '#eeebe3',
        success: '#15803d',
        'on-success': '#ffffff',
        warning: '#a16207',
        'on-warning': '#fffef9',
        error: '#b91c1c',
        'on-error': '#ffffff',
        slate: '#64748b',
      },
      fontFamily: {
        display: ['Poppins', 'system-ui', 'sans-serif'],
        body: ['Poppins', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-xl': ['72px', { letterSpacing: '-0.035em', fontWeight: '700', lineHeight: '1.05' }],
        'display-lg': ['56px', { letterSpacing: '-0.025em', fontWeight: '700', lineHeight: '1.1' }],
        'headline-lg': ['40px', { letterSpacing: '-0.02em', fontWeight: '600', lineHeight: '1.15' }],
        'headline-md': ['28px', { letterSpacing: '-0.015em', fontWeight: '600', lineHeight: '1.2' }],
        'headline-sm': ['20px', { letterSpacing: '-0.01em', fontWeight: '600', lineHeight: '1.3' }],
        'body-lg': ['17px', { lineHeight: '1.6' }],
        'body-md': ['15px', { lineHeight: '1.55' }],
        'body-sm': ['13px', { lineHeight: '1.5' }],
        'label-md': ['12px', { letterSpacing: '0.06em', fontWeight: '600', lineHeight: '1.2' }],
        'label-sm': ['10px', { letterSpacing: '0.08em', fontWeight: '600', lineHeight: '1.2' }],
        mono: ['13px', { fontWeight: '400', lineHeight: '1.5' }],
        'mono-sm': ['11px', { letterSpacing: '0.04em', fontWeight: '500', lineHeight: '1.4' }],
      },
      borderRadius: {
        none: '0px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        full: '9999px',
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '24px',
        '6': '32px',
        '7': '48px',
        '8': '64px',
        '9': '96px',
      },
      letterSpacing: {
        tightest: '-0.04em',
      },
      maxWidth: {
        '8xl': '88rem',
      },
    },
  },
  plugins: [],
};
